---
# vi:ts=2 sw=2 et:
#
# Docs: https://packit.dev/docs/


srpm_build_deps:
  - git

actions:
  get-current-version:
    - bash -c "cat .version"
  create-archive:
    - bash -c "git archive --prefix=libnccl-net-ofi/ --format=tgz --output=libnccl-net-ofi_${PACKIT_PROJECT_VERSION}.tar.gz HEAD src/ include/ doc/ m4/ tests/ topology/ configure.ac Makefile.am LICENSE NOTICE .version && echo libnccl-net-ofi_${PACKIT_PROJECT_VERSION}.tar.gz"

specfile_path: libnccl-net-ofi.spec
upstream_package_name: libnccl-net-ofi
downstream_package_name: libnccl-net-ofi
release_suffix: "{PACKIT_PROJECT_BRANCH}"
update_release: false
