---
fail_fast: false
exclude: |
    (?x)^(
      include/nccl-headers
    ).*$
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-merge-conflict
          - id: detect-private-key
          - id: mixed-line-ending
          - id: check-added-large-files
          - id: check-shebang-scripts-are-executable
    - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
      rev: 0.2.3
      hooks:
          - id: yamlfmt
    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.0
      hooks:
          - id: actionlint
    - repo: https://github.com/compilerla/conventional-pre-commit
      rev: v3.2.0
      hooks:
          - id: conventional-pre-commit
            stages: [commit-msg]
            args: [misc, build, ci, docs, feat, fix, perf, refactor, style, test, nit]
    - repo: https://github.com/shellcheck-py/shellcheck-py
      rev: v0.10.0.1
      hooks:
          - id: shellcheck
