---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: pool-amd64
  annotations:
    kubernetes.io/description: "Build nodepool for amd64 workloads"
spec:
  disruption:
    consolidateAfter: 1m0s
    consolidationPolicy: WhenEmptyOrUnderutilized
    #expireAfter: 8h
  limits:
    cpu: 2048
  template:
    metadata: {}
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: bottlerocket
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: pool-arm64
  annotations:
    kubernetes.io/description: "Build nodepool for amd64 workloads"
spec:
  disruption:
    consolidateAfter: 1m0s
    consolidationPolicy: WhenEmptyOrUnderutilized
    #expireAfter: 8h
  limits:
    cpu: 2048
  template:
    metadata: {}
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["arm64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: bottlerocket
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: bottlerocket
spec:
  role: "KarpenterNodeRole-ect-build"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ect-build"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "ect-build"
  amiSelectorTerms:
    - alias: bottlerocket@latest
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeType: gp3
        volumeSize: 10Gi
        deleteOnTermination: true
    - deviceName: /dev/xvdb
      ebs:
        volumeType: gp3
        volumeSize: 40Gi 
        deleteOnTermination: true
