---
apiVersion: karpenter.sh/v1
kind: Provisioner
metadata:
  name: management
spec:
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values: ["on-demand"]
  limits:
    resources:
      cpu: 1000
  provider:
    instanceProfile: eksctl-KarpenterNodeInstanceProfile-ect-build
    subnetSelector:
      karpenter.sh/discovery: ect-build
    securityGroupSelector:
      karpenter.sh/discovery: ect-build
  ttlSecondsAfterEmpty: 30
